Import("env")

sources = ["main.cc", "bitstream.cc", "mp3_frameheader.cc", "mp3_framesync.cc"]

test = env.Program(
    "test",
    sources + env["OBJ_COMMON"] + env["CODECS"]["mp3"]["objects"],
    LIBS = ["boost_unit_test_framework"]
)

test_alias = env.Alias("test", [test], test[0].abspath)
AlwaysBuild(test_alias)
